//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiBayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscricao
    {
        public int id_inscricao { get; set; }
        public int id_usuario { get; set; }
        public int id_vaga { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual vagas vagas { get; set; }
    }
}
