//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiBayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bayerEntities : DbContext
    {
        public bayerEntities()
            : base("name=bayerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<inscricao> inscricao { get; set; }
        public virtual DbSet<recrutador> recrutador { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<vagas> vagas { get; set; }
    }
}
