//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiBayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class recrutador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recrutador()
        {
            this.vagas = new HashSet<vagas>();
        }
    
        public int id_recrutador { get; set; }
        public string nome { get; set; }
        public string registro { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string sobrenome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vagas> vagas { get; set; }
    }
}
